### ISSUE TITLE
config.sample defined CONSTANTS?

### ISSUE THREAD

**Issue by twmoore3rd** [dustball/opencrisisline#16]
Late in bringing this up as my head has been in Python for the past couple of years which doesn't have constants.

Particularly for the variable assignments in config.sample, is there any reason we are not using defined CONSTANTs in the code, i.e., define(DFW, "Drink Your Water");

Must admit that it is personal preference but does provide another layer of code security so statements such as `if (DFW = "FML")` will throw an error.

**Comment by dustball** [comment]
I don't have strong feelings either way.  IMHO code looks cleaner the "wrong" way but you are right about the benefit regarding accidental assignment.
